### ISSUE TITLE
Dispose issue in provider architecture part 2

### ISSUE THREAD

**Issue by NeKoFu** [FilledStacks/flutter-tutorials#6]
Hi,

In [provider architecture pt2](https://github.com/FilledStacks/flutter-tutorials/blob/master/012-provider-architecture-pt2/2-final) there is an issue when views and widgets derived from BaseView are disposed.

To reproduce:
Launch the app, login to fetch and show posts on the homeview then go back to login screen.
You will see the FlutterError exception in the debug console content thrown by ChangeNotifier.

``` 
I/flutter (30244): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════

I/flutter (30244): The following assertion was thrown while finalizing the widget tree:

I/flutter (30244): A HomeModel was used after being disposed.

I/flutter (30244): Once you have called dispose() on a HomeModel, it can no longer be used.

I/flutter (30244):

I/flutter (30244): When the exception was thrown, this was the stack:

I/flutter (30244): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 

I/flutter (30244): #1      ChangeNotifier._debugAssertNotDisposed 

I/flutter (30244): #2      ChangeNotifier.dispose 

I/flutter (30244): #3      _BaseViewState.dispose 

I/flutter (30244): #4      StatefulElement.unmount 

I/flutter (30244): #5      _InactiveElements._unmount 

I/flutter (30244): #6      _InactiveElements._unmount.<anonymous closure> 

I/flutter (30244): #7      ComponentElement.visitChildren 

I/flutter (30244): #8      _InactiveElements._unmount 
...
```

**Comment by FilledStacks** [comment]
Hi, this should be fixed in the latest code. If you register the HomeModel as a Factory this should go away?. Unless it's the new Dispose I mentioned to add in the BaseView. I'll look into it when I get some time and will update here when I find a fix. 

Thanks for letting me know.

**Comment by FilledStacks** [comment]
Sorry about the close

**Comment by NeKoFu** [comment]
In fact, I get the issue firstly on my own version then I have tried your own code yesterday and the issue appear in both codes.

But I will refetch your repository immediatly and try again.

**Comment by NeKoFu** [comment]
I checked, HomeModel is registred as a Factory in the _locator.dart_ and issue still here.

**Comment by FilledStacks** [comment]
I see. I'll check it out tonight while I'm busy writing the new tutorial and see what the problem is. Will update as soon as I find and fix it.

**Comment by NeKoFu** [comment]
Ok. By the way, thank you for your greats tutorials on Flutter. It helps and inspires me a lot.

**Comment by FilledStacks** [comment]
Thanks man. It makes me happy to hear that.

**Comment by GIfatahTH** [comment]
ViewModels extend ChangeNotifier and the latter is disposed by flutter framework when the HomeView is popped out. Explicitly disposing HomeView and calling super.dispose will dispose the ChangeNotifier for the second time which it is not allowed. 
@FilledStacks add dispose method to BaseView after a discussion with the creator of the provider package. But it is the StreamController in the AuthenticationService that needs to be disposed and AuthenticationService does not extend BaseModel.

**Comment by FilledStacks** [comment]
@GIfatahTH Thanks for looking into it, that makes sense. So I'll remove that call since it's already being called. 

On the stream controller, it definitely should not be getting disposed during the entire lifetime of the app. It's used on the Home and posts view so disposing it at anytime would not be beneficial to the app. 

The main problem was the additional dispose call in the base view, that was a silly mistake on my side. I should have realised it's already being called by provider and all we have to do is just override in the Model and dispose resources that we might want to dispose there.

Thanks for looking into it. Much appreciated.

**Comment by FilledStacks** [comment]
The reason for the LikeButtonModel exception is because the provider package already disposes the ChangeNotifier (our model) so all we have to do is override the dispose call inside the model and do our clean up in there.

**Comment by GIfatahTH** [comment]
Yes. for this particular case the stream controller should not be getting disposed during the entire lifetime of the app. But what about the general cas when I want to dispose resources from services.

**Comment by FilledStacks** [comment]
In this architecture if a stream is being used, outside of the provider. Through a model for instance. It means the subscription will live in the model. If you want to revoke that subscription to clean up the stream you'll override dispose in the model and do that. 

There's no other scenario where you provide a stream to the entire app and you want to dispose that stream while the app is running. So any cleanup will be done per model, if you have a subscription to a stream when every instance is created for that model. 

```dart
class PostModel extends BaseModel {

MyService _service = locator<MyService>();

  StreamSubscription<Post> subscription;

  PostModel(){
    subscription = _service.onceOffStream.listen((data){
    // things
    })
  }

  @override 
  void dispose() {
    super.dispose()
    subscription.cancel();
  }
}
```
